name: 寧の小棧
author: 且宁
url: https://ning-qie.github.io
baseurl: 
resume_site: https://ning-qie.github.io
description: 
github_username: Ning-Qie
github: 1425431429@qq.com
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
